import { NextRequest, NextResponse } from "next/server";
import { prisma } from "@/lib/db";

type SeedBody = {
  total?: number;
};

export async function POST(request: NextRequest) {
  try {
    if (process.env.NODE_ENV === "production") {
      return NextResponse.json(
        { status: "error", message: "Seed endpoint disabled in production" },
        { status: 403 }
      );
    }

    const body = (await request.json().catch(() => ({}))) as SeedBody;
    const total = Math.min(Math.max(Number(body.total ?? 6), 3), 30);

    let event = await prisma.event.findFirst({
      where: { isActive: true },
      orderBy: { date: "asc" },
    });

    if (!event) {
      event = await prisma.event.create({
        data: {
          name: "TEDxUC 2026 Main Event",
          type: "Main Event",
          date: new Date("2026-05-10T09:00:00.000Z"),
          quota: 500,
          registeredCount: 0,
          price: 150000,
          description: "Autogenerated dev event for payment testing",
          requireFoodAllergy: true,
          isActive: true,
        },
      });
    }

    const now = Date.now();
    const statuses = ["verifying", "rejected", "approved"] as const;
    const created = {
      registrations: 0,
      payments: 0,
      verifying: 0,
      rejected: 0,
      approved: 0,
    };

    for (let i = 0; i < total; i += 1) {
      const status = statuses[i % statuses.length];
      const suffix = `${now}-${i + 1}`;
      const regNumber = `DEV-${suffix}`;

      const registration = await prisma.registration.create({
        data: {
          fullName: `Payment Tester ${i + 1}`,
          email: `payment-tester-${suffix}@example.com`,
          phoneNumber: `0812${String(100000 + i).padStart(6, "0")}`,
          gender: i % 2 === 0 ? "Laki-laki" : "Perempuan",
          age: 20 + (i % 8),
          foodAllergy: "-",
          eventId: event.id,
          registrationNumber: regNumber,
          status: status === "approved" ? "paid" : "pending",
          qrCode: status === "approved" ? `TEDx26-${regNumber}-DEV` : null,
        },
      });

      await prisma.payment.create({
        data: {
          registrationId: registration.id,
          amount: event.price,
          paymentMethod: i % 2 === 0 ? "BCA" : "QRIS",
          status,
          proofUrl: "https://picsum.photos/seed/tedx-payment-proof/640/900",
          proofSenderName: `Sender ${i + 1}`,
          rejectionReason:
            status === "rejected" ? "Sample rejected submission for admin test." : null,
          paymentDate: new Date(),
        },
      });

      created.registrations += 1;
      created.payments += 1;
      created[status] += 1;
    }

    return NextResponse.json({
      status: "success",
      message: "Payment test data generated",
      data: {
        eventId: event.id,
        created,
      },
    });
  } catch (error) {
    console.error("Seed payment test data error:", error);
    return NextResponse.json(
      { status: "error", message: "Failed to generate test data" },
      { status: 500 }
    );
  }
}

export async function DELETE() {
  try {
    if (process.env.NODE_ENV === "production") {
      return NextResponse.json(
        { status: "error", message: "Seed endpoint disabled in production" },
        { status: 403 }
      );
    }

    const seededRegistrations = await prisma.registration.findMany({
      where: {
        email: { startsWith: "payment-tester-" },
      },
      select: { id: true },
    });

    const registrationIds = seededRegistrations.map((r) => r.id);

    if (registrationIds.length > 0) {
      await prisma.payment.deleteMany({
        where: {
          registrationId: { in: registrationIds },
        },
      });
    }

    const deletedRegistrations = await prisma.registration.deleteMany({
      where: {
        email: { startsWith: "payment-tester-" },
      },
    });

    return NextResponse.json({
      status: "success",
      message: "Seeded payment test data removed",
      data: {
        deletedRegistrations: deletedRegistrations.count,
      },
    });
  } catch (error) {
    console.error("Delete seeded payment test data error:", error);
    return NextResponse.json(
      { status: "error", message: "Failed to remove test data" },
      { status: 500 }
    );
  }
}
